version: 2

sources:
  - name: raw_ohlcs
    meta:
      external_location: "read_parquet('{{ env_var('EQUITY_SENTIMENT_DATA_DIR', '../data') }}/processed/ohlcs/stg_ohlcs-*.parquet')"
    tables:
      - name: ohlcs

  - name: raw_news
    meta:
      external_location: "read_parquet('{{ env_var('EQUITY_SENTIMENT_DATA_DIR', '../data') }}/processed/news/stg_news-*.parquet')"
    tables:
      - name: news
  - name: raw_companies
    meta:
      external_location: "read_parquet('{{ env_var('EQUITY_SENTIMENT_DATA_DIR', '../data') }}/processed/companies/stg_companies.parquet')"
    tables:
      - name: companies

  - name: raw_factors
    meta:
      external_location: "read_parquet('{{ env_var('EQUITY_SENTIMENT_DATA_DIR', '../data') }}/processed/factors/fama_french_daily.parquet')"
    tables:
      - name: fama_french_daily
